env:
  global:
    - XDEBUG_MODE=coverage

language: php

php:
  - 7.3
  - 7.4
  - 8.0

jobs:
  allow_failures:
    - php: 8.0

git:
  depth: false

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover="build/logs/clover.xml" --log-junit="build/logs/phpunit.xml" Tests
  - composer style
  - sonar-scanner

addons:
  sonarcloud:
    organization: "fresh-advance"
    token:
      secure: "pm/6A1+VTBNnqnMDJLl0NOq+yQDvVoj/W3KT+agF7eqHwRHwKf9/SFjlfPzeslk+CdPW4L+jtDp7B2DsCpelCaEVAZAE0N7Ia4ai8iBSKCkInuxzO5wX1dDtzKyYpLfFf6Fs68xmCJsOT+HHLk/5McNH5VZ8HoQEwmBJLGb75Okn4nyaDSEEXTMehwLjXD632bXDagtUfuZ5wjreuiryAE4ZYPIGM3PmXREmlMIzrp0D69YaqpHEiobk9nAXOt0UdYO43A0ZEvFFJJ/62UWP0ZkQ78K9rQnhjRMYrfcwhImVu1UFl4Zjq01A6QI81T3JQM6QfcqvYG1G0gTzNeu0nZETSTx4W/Kw+7AIukCOGbG6vScCICZcX26Nub9OtAwKhqnhJBChnZyrSwIVEePHWECSeaNjDojQk12lwjAbqXqa6XOaXkHfKWQXpFnW3mhvOoK2EGW4xLUPey9Rfsy8G+YUKEv47HjfkmLauVU9GAov2uUiOJdPFAQA1bTX3qi29aO1j6VJtFIWEhdL8vbRDDXiQ4yW9i6vi6X2v5RvrIYOsnMa9pejDo/Fl2rruSXIllZIul99kwsO2ZNV3NmbQd7B7NUzs6tJ5bWydsFsFZDwBSrpLgP41ejlyUO1MaeZOk2IiMOwjpQApQ5mSHxkGSnFMvTBmG4qqTLt7IRTqto="