language: php

php:
  - 7.3
  - 7.4

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover="build/logs/clover.xml" Tests
  - composer style
  - sonar-scanner

addons:
  sonarcloud:
    organization: "fresh-advance"
    token:
      secure: $SONARCODE